// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_latency_ap_fixed_ap_fixed_config2_0_0 (
        ap_ready,
        data_V_read,
        ap_return
);


output   ap_ready;
input  [15:0] data_V_read;
output  [14:0] ap_return;

assign ap_ready = 1'b1;

assign ap_return = {{data_V_read[15:1]}};

endmodule //dense_latency_ap_fixed_ap_fixed_config2_0_0
