// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_latency_ap_fixed_ap_fixed_config2_0_0_0 (
        ap_ready,
        data_V_read,
        ap_return
);


output   ap_ready;
input  [15:0] data_V_read;
output  [14:0] ap_return;

wire  signed [15:0] sext_ln1118_fu_44_p0;
wire  signed [15:0] shl_ln_fu_48_p1;
wire   [18:0] shl_ln_fu_48_p3;
wire  signed [19:0] sext_ln1118_1_fu_56_p1;
wire  signed [19:0] sext_ln1118_fu_44_p1;
wire   [19:0] sub_ln1118_fu_60_p2;

assign ap_ready = 1'b1;

assign ap_return = {{sub_ln1118_fu_60_p2[19:5]}};

assign sext_ln1118_1_fu_56_p1 = $signed(shl_ln_fu_48_p3);

assign sext_ln1118_fu_44_p0 = data_V_read;

assign sext_ln1118_fu_44_p1 = sext_ln1118_fu_44_p0;

assign shl_ln_fu_48_p1 = data_V_read;

assign shl_ln_fu_48_p3 = {{shl_ln_fu_48_p1}, {3'd0}};

assign sub_ln1118_fu_60_p2 = ($signed(sext_ln1118_1_fu_56_p1) - $signed(sext_ln1118_fu_44_p1));

endmodule //dense_latency_ap_fixed_ap_fixed_config2_0_0_0
