-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dense_latency_ap_fixed_ap_fixed_config2_0_0_0 is
port (
    ap_ready : OUT STD_LOGIC;
    data_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (14 downto 0) );
end;


architecture behav of dense_latency_ap_fixed_ap_fixed_config2_0_0_0 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal sext_ln1118_fu_44_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln_fu_48_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln_fu_48_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln1118_1_fu_56_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln1118_fu_44_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal sub_ln1118_fu_60_p2 : STD_LOGIC_VECTOR (19 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= sub_ln1118_fu_60_p2(19 downto 5);
        sext_ln1118_1_fu_56_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_48_p3),20));

    sext_ln1118_fu_44_p0 <= data_V_read;
        sext_ln1118_fu_44_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1118_fu_44_p0),20));

    shl_ln_fu_48_p1 <= data_V_read;
    shl_ln_fu_48_p3 <= (shl_ln_fu_48_p1 & ap_const_lv3_0);
    sub_ln1118_fu_60_p2 <= std_logic_vector(signed(sext_ln1118_1_fu_56_p1) - signed(sext_ln1118_fu_44_p1));
end behav;
