compiler:
  basic:
    PATH: "/usr/bin"
    LD_LIBRARY_PATH: '/usr/lib/x86_64-linux-gnu:/usr/lib32:'
    LIBRARY_PATH: '/usr/lib/x86_64-linux-gnu:/usr/lib32:'
  vivado:
    CC: "/usr/bin/gcc-4.9"
    CXX: "/usr/bin/g++-4.9"
    CPLUS_INCLUDE_PATH: "/usr/include:/usr/include/c++/4.9:/usr/include/x86_64-linux-gnu"